package org.lint.Entity;

public class Cityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.areaID
     *
     * @mbg.generated
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.areaName
     *
     * @mbg.generated
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cityarea.cityID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.areaID
     *
     * @return the value of cityarea.areaID
     *
     * @mbg.generated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.areaID
     *
     * @param areaid the value for cityarea.areaID
     *
     * @mbg.generated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.areaName
     *
     * @return the value of cityarea.areaName
     *
     * @mbg.generated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.areaName
     *
     * @param areaname the value for cityarea.areaName
     *
     * @mbg.generated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cityarea.cityID
     *
     * @return the value of cityarea.cityID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cityarea.cityID
     *
     * @param cityid the value for cityarea.cityID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }
}