package org.lint.Entity;

public class Deliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePID
     *
     * @mbg.generated
     */
    private String depid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePName
     *
     * @mbg.generated
     */
    private String depname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.provinceID
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.cityID
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgID
     *
     * @mbg.generated
     */
    private String mgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePTel
     *
     * @mbg.generated
     */
    private String deptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    private String depaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePID
     *
     * @return the value of deliveryplace.dePID
     *
     * @mbg.generated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePID
     *
     * @param depid the value for deliveryplace.dePID
     *
     * @mbg.generated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePName
     *
     * @return the value of deliveryplace.dePName
     *
     * @mbg.generated
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePName
     *
     * @param depname the value for deliveryplace.dePName
     *
     * @mbg.generated
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.provinceID
     *
     * @return the value of deliveryplace.provinceID
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.provinceID
     *
     * @param provinceid the value for deliveryplace.provinceID
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.cityID
     *
     * @return the value of deliveryplace.cityID
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.cityID
     *
     * @param cityid the value for deliveryplace.cityID
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgID
     *
     * @return the value of deliveryplace.mgID
     *
     * @mbg.generated
     */
    public String getMgid() {
        return mgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgID
     *
     * @param mgid the value for deliveryplace.mgID
     *
     * @mbg.generated
     */
    public void setMgid(String mgid) {
        this.mgid = mgid == null ? null : mgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePTel
     *
     * @return the value of deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public String getDeptel() {
        return deptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePTel
     *
     * @param deptel the value for deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public void setDeptel(String deptel) {
        this.deptel = deptel == null ? null : deptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePAddr
     *
     * @return the value of deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public String getDepaddr() {
        return depaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePAddr
     *
     * @param depaddr the value for deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public void setDepaddr(String depaddr) {
        this.depaddr = depaddr == null ? null : depaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.Comment
     *
     * @return the value of deliveryplace.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.Comment
     *
     * @param comment the value for deliveryplace.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}