package org.lint.Entity;

import java.math.BigDecimal;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderID
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPName
     *
     * @mbg.generated
     */
    private String postpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPTel
     *
     * @mbg.generated
     */
    private String postptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postPAddr
     *
     * @mbg.generated
     */
    private String postpaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPName
     *
     * @mbg.generated
     */
    private String getpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPTel
     *
     * @mbg.generated
     */
    private String getptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.getPAddr
     *
     * @mbg.generated
     */
    private String getpaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsName
     *
     * @mbg.generated
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsWeight
     *
     * @mbg.generated
     */
    private Integer goodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderType
     *
     * @mbg.generated
     */
    private String ordertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderState
     *
     * @mbg.generated
     */
    private String orderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.deliceryPrice
     *
     * @mbg.generated
     */
    private BigDecimal deliceryprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalPrice
     *
     * @mbg.generated
     */
    private String totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderID
     *
     * @return the value of orders.orderID
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderID
     *
     * @param orderid the value for orders.orderID
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPName
     *
     * @return the value of orders.postPName
     *
     * @mbg.generated
     */
    public String getPostpname() {
        return postpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPName
     *
     * @param postpname the value for orders.postPName
     *
     * @mbg.generated
     */
    public void setPostpname(String postpname) {
        this.postpname = postpname == null ? null : postpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPTel
     *
     * @return the value of orders.postPTel
     *
     * @mbg.generated
     */
    public String getPostptel() {
        return postptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPTel
     *
     * @param postptel the value for orders.postPTel
     *
     * @mbg.generated
     */
    public void setPostptel(String postptel) {
        this.postptel = postptel == null ? null : postptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postPAddr
     *
     * @return the value of orders.postPAddr
     *
     * @mbg.generated
     */
    public String getPostpaddr() {
        return postpaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postPAddr
     *
     * @param postpaddr the value for orders.postPAddr
     *
     * @mbg.generated
     */
    public void setPostpaddr(String postpaddr) {
        this.postpaddr = postpaddr == null ? null : postpaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPName
     *
     * @return the value of orders.getPName
     *
     * @mbg.generated
     */
    public String getGetpname() {
        return getpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPName
     *
     * @param getpname the value for orders.getPName
     *
     * @mbg.generated
     */
    public void setGetpname(String getpname) {
        this.getpname = getpname == null ? null : getpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPTel
     *
     * @return the value of orders.getPTel
     *
     * @mbg.generated
     */
    public String getGetptel() {
        return getptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPTel
     *
     * @param getptel the value for orders.getPTel
     *
     * @mbg.generated
     */
    public void setGetptel(String getptel) {
        this.getptel = getptel == null ? null : getptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.getPAddr
     *
     * @return the value of orders.getPAddr
     *
     * @mbg.generated
     */
    public String getGetpaddr() {
        return getpaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.getPAddr
     *
     * @param getpaddr the value for orders.getPAddr
     *
     * @mbg.generated
     */
    public void setGetpaddr(String getpaddr) {
        this.getpaddr = getpaddr == null ? null : getpaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsName
     *
     * @return the value of orders.goodsName
     *
     * @mbg.generated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsName
     *
     * @param goodsname the value for orders.goodsName
     *
     * @mbg.generated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsWeight
     *
     * @return the value of orders.goodsWeight
     *
     * @mbg.generated
     */
    public Integer getGoodsweight() {
        return goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsWeight
     *
     * @param goodsweight the value for orders.goodsWeight
     *
     * @mbg.generated
     */
    public void setGoodsweight(Integer goodsweight) {
        this.goodsweight = goodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderType
     *
     * @return the value of orders.orderType
     *
     * @mbg.generated
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderType
     *
     * @param ordertype the value for orders.orderType
     *
     * @mbg.generated
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderState
     *
     * @return the value of orders.orderState
     *
     * @mbg.generated
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderState
     *
     * @param orderstate the value for orders.orderState
     *
     * @mbg.generated
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate == null ? null : orderstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.transportPrice
     *
     * @return the value of orders.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.transportPrice
     *
     * @param transportprice the value for orders.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportprice(BigDecimal transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.deliceryPrice
     *
     * @return the value of orders.deliceryPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDeliceryprice() {
        return deliceryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.deliceryPrice
     *
     * @param deliceryprice the value for orders.deliceryPrice
     *
     * @mbg.generated
     */
    public void setDeliceryprice(BigDecimal deliceryprice) {
        this.deliceryprice = deliceryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalPrice
     *
     * @return the value of orders.totalPrice
     *
     * @mbg.generated
     */
    public String getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalPrice
     *
     * @param totalprice the value for orders.totalPrice
     *
     * @mbg.generated
     */
    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice == null ? null : totalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Comment
     *
     * @return the value of orders.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Comment
     *
     * @param comment the value for orders.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}