package org.lint.Entity;

import java.math.BigDecimal;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeID
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeName
     *
     * @mbg.generated
     */
    private String routename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startProvice
     *
     * @mbg.generated
     */
    private String startprovice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startCity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endProwince
     *
     * @mbg.generated
     */
    private String endprowince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endCity
     *
     * @mbg.generated
     */
    private String endcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midProwince
     *
     * @mbg.generated
     */
    private String midprowince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midCity
     *
     * @mbg.generated
     */
    private String midcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeID
     *
     * @return the value of route.routeID
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeID
     *
     * @param routeid the value for route.routeID
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeName
     *
     * @return the value of route.routeName
     *
     * @mbg.generated
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeName
     *
     * @param routename the value for route.routeName
     *
     * @mbg.generated
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startProvice
     *
     * @return the value of route.startProvice
     *
     * @mbg.generated
     */
    public String getStartprovice() {
        return startprovice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startProvice
     *
     * @param startprovice the value for route.startProvice
     *
     * @mbg.generated
     */
    public void setStartprovice(String startprovice) {
        this.startprovice = startprovice == null ? null : startprovice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startCity
     *
     * @return the value of route.startCity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startCity
     *
     * @param startcity the value for route.startCity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endProwince
     *
     * @return the value of route.endProwince
     *
     * @mbg.generated
     */
    public String getEndprowince() {
        return endprowince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endProwince
     *
     * @param endprowince the value for route.endProwince
     *
     * @mbg.generated
     */
    public void setEndprowince(String endprowince) {
        this.endprowince = endprowince == null ? null : endprowince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endCity
     *
     * @return the value of route.endCity
     *
     * @mbg.generated
     */
    public String getEndcity() {
        return endcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endCity
     *
     * @param endcity the value for route.endCity
     *
     * @mbg.generated
     */
    public void setEndcity(String endcity) {
        this.endcity = endcity == null ? null : endcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midProwince
     *
     * @return the value of route.midProwince
     *
     * @mbg.generated
     */
    public String getMidprowince() {
        return midprowince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midProwince
     *
     * @param midprowince the value for route.midProwince
     *
     * @mbg.generated
     */
    public void setMidprowince(String midprowince) {
        this.midprowince = midprowince == null ? null : midprowince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midCity
     *
     * @return the value of route.midCity
     *
     * @mbg.generated
     */
    public String getMidcity() {
        return midcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midCity
     *
     * @param midcity the value for route.midCity
     *
     * @mbg.generated
     */
    public void setMidcity(String midcity) {
        this.midcity = midcity == null ? null : midcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.transportPrice
     *
     * @return the value of route.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.transportPrice
     *
     * @param transportprice the value for route.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportprice(BigDecimal transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.Comment
     *
     * @return the value of route.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.Comment
     *
     * @param comment the value for route.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}